CREATE TYPE "public"."estado_remesa" AS ENUM('enviada', 'recibida');--> statement-breakpoint
CREATE TABLE "remesas" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"numero" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "remesas_numero_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"moneda" "moneda" NOT NULL,
	"estado" "estado_remesa" DEFAULT 'enviada' NOT NULL,
	"fecha_envio" date NOT NULL,
	"enviado_por_id" uuid,
	"fecha_recepcion" timestamp with time zone,
	"recibido_por_id" uuid,
	"notas" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid
);
--> statement-breakpoint
ALTER TABLE "pagos" ADD COLUMN "remesa_id" uuid;--> statement-breakpoint
ALTER TABLE "remesas" ADD CONSTRAINT "remesas_enviado_por_id_usuarios_id_fk" FOREIGN KEY ("enviado_por_id") REFERENCES "public"."usuarios"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remesas" ADD CONSTRAINT "remesas_recibido_por_id_usuarios_id_fk" FOREIGN KEY ("recibido_por_id") REFERENCES "public"."usuarios"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remesas" ADD CONSTRAINT "remesas_created_by_usuarios_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."usuarios"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_remesas_numero_unico" ON "remesas" USING btree ("numero");--> statement-breakpoint
CREATE INDEX "idx_remesas_estado" ON "remesas" USING btree ("estado");--> statement-breakpoint
ALTER TABLE "pagos" ADD CONSTRAINT "pagos_remesa_id_remesas_id_fk" FOREIGN KEY ("remesa_id") REFERENCES "public"."remesas"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_pagos_remesa" ON "pagos" USING btree ("remesa_id");